[package]
name = "vm"
version = "0.1.0"
authors = ["Andrew Craig <andy.peter.craig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
log = "0.4.8"